#!/bin/bash

rsync -rave "ssh -i ~/.ssh/qnzl" infra/reader.conf root@0.0.0.0:/etc/supervisor/conf.d;
rsync -rave "ssh -i ~/.ssh/qnzl" infra/reader root@0.0.0.0:/etc/nginx/sites-available;

ssh root@0.0.0.0 -i ~/.ssh/qnzl "ln -s /etc/nginx/sites-available/reader /etc/nginx/sites-enabled/ && sudo service nginx reload && sudo service nginx restart && sudo supervisorctl reload && sudo supervisorctl restart reader && certbot --nginx"
